spring.application.name=S3Tutorial


cloud.aws.credentials.secret-key=your-secret-key

cloud.aws.credentials.access-key=your-access-key

cloud.aws.region=us-east-1

cloud.aws.bucket.name=s3tutorial-purpose